package com.siarheikrupenich.domain

import com.siarheikrupenich.testrepo.repository.model.Owner
import com.siarheikrupenich.testrepo.repository.model.Permissions
import com.siarheikrupenich.testrepo.repository.model.Repo

object DomainTestObjects {

    val repos = listOf(
        Repo(
            id = 1,
            name = "desc 1",
            fullName = "Full name 1",
            private = false,
            owner = Owner(
                login = "",
                id = 1,
                avatarUrl = "",
                gravatarId = "",
                url = "",
                htmlUrl = "",
                followersUrl = "",
                followingUrl = "",
                gistsUrl = "",
                starredUrl = "",
                subscriptionsUrl = "",
                organizationsUrl = "",
                reposUrl = "",
                eventsUrl = "",
                receivedEventsUrl = "",
                type = "",
                siteAdmin = false,
            ),
            htmlUrl = "",
            description = null,
            fork = false,
            url = "",
            createdAt = "",
            updatedAt = "",
            pushedAt = "",
            gitUrl = "",
            sshUrl = "",
            cloneUrl = "",
            svnUrl = "",
            homepage = null,
            size = 1200,
            stargazersCount = 10,
            watchersCount = 10,
            language = "",
            hasIssues = true,
            hasProjects = true,
            hasDownloads = true,
            hasWiki = false,
            hasPages = false,
            hasDiscussions = true,
            forksCount = 5,
            mirrorUrl = null,
            archived = true,
            disabled = false,
            openIssuesCount = 10,
            license = null,
            allowForking = true,
            isTemplate = true,
            webCommitSignoffRequired = false,
            topics = listOf(),
            visibility = "",
            forks = 10,
            openIssues = 10,
            watchers = 5,
            defaultBranch = "",
            permissions = Permissions(
                admin = false,
                maintain = false,
                push = false,
                triage = false,
                pull = true
            ),
        ),
        Repo(
            id = 2,
            name = "desc 2",
            fullName = "Full name 2",
            private = false,
            owner = Owner(
                login = "",
                id = 1,
                avatarUrl = "",
                gravatarId = "",
                url = "",
                htmlUrl = "",
                followersUrl = "",
                followingUrl = "",
                gistsUrl = "",
                starredUrl = "",
                subscriptionsUrl = "",
                organizationsUrl = "",
                reposUrl = "",
                eventsUrl = "",
                receivedEventsUrl = "",
                type = "",
                siteAdmin = false,
            ),
            htmlUrl = "",
            description = null,
            fork = false,
            url = "",
            createdAt = "",
            updatedAt = "",
            pushedAt = "",
            gitUrl = "",
            sshUrl = "",
            cloneUrl = "",
            svnUrl = "",
            homepage = null,
            size = 1200,
            stargazersCount = 10,
            watchersCount = 10,
            language = "",
            hasIssues = true,
            hasProjects = true,
            hasDownloads = true,
            hasWiki = false,
            hasPages = false,
            hasDiscussions = true,
            forksCount = 5,
            mirrorUrl = null,
            archived = true,
            disabled = false,
            openIssuesCount = 10,
            license = null,
            allowForking = true,
            isTemplate = true,
            webCommitSignoffRequired = false,
            topics = listOf(),
            visibility = "",
            forks = 10,
            openIssues = 10,
            watchers = 5,
            defaultBranch = "",
            permissions = Permissions(
                admin = false,
                maintain = false,
                push = false,
                triage = false,
                pull = true
            ),
        ),
        Repo(
            id = 3,
            name = "desc 3",
            fullName = "Full name 3",
            private = false,
            owner = Owner(
                login = "",
                id = 1,
                avatarUrl = "",
                gravatarId = "",
                url = "",
                htmlUrl = "",
                followersUrl = "",
                followingUrl = "",
                gistsUrl = "",
                starredUrl = "",
                subscriptionsUrl = "",
                organizationsUrl = "",
                reposUrl = "",
                eventsUrl = "",
                receivedEventsUrl = "",
                type = "",
                siteAdmin = false,
            ),
            htmlUrl = "",
            description = null,
            fork = false,
            url = "",
            createdAt = "",
            updatedAt = "",
            pushedAt = "",
            gitUrl = "",
            sshUrl = "",
            cloneUrl = "",
            svnUrl = "",
            homepage = null,
            size = 1200,
            stargazersCount = 10,
            watchersCount = 10,
            language = "",
            hasIssues = true,
            hasProjects = true,
            hasDownloads = true,
            hasWiki = false,
            hasPages = false,
            hasDiscussions = true,
            forksCount = 5,
            mirrorUrl = null,
            archived = true,
            disabled = false,
            openIssuesCount = 10,
            license = null,
            allowForking = true,
            isTemplate = true,
            webCommitSignoffRequired = false,
            topics = listOf(),
            visibility = "",
            forks = 10,
            openIssues = 10,
            watchers = 5,
            defaultBranch = "",
            permissions = Permissions(
                admin = false,
                maintain = false,
                push = false,
                triage = false,
                pull = true
            ),
        ),
    )
}
